name: BasicLab
summary: This is a lab deployment using Bicep.
description: Deploys a basic lab setup.
templatePath: main.bicep
parameters:
- id: "location"
  name: "location"
  description: "Location to deploy the environment resources"
  default: "swedencentral"
  type: "string"
runner: Bicep