name: DevBoxLab
summary: This is a lab environment with a basic setup and DevBox.
description: Deploys a vNet, Bastion, NAT Gateway and resources for creating Dev Boxes connected to the lab.
templatePath: main.bicep
runner: Bicep
parameters:
- id: "location"
  name: "Location"
  description: "Location to deploy the environment resources"
  default: "swedencentral"
  type: "string"
- id: "projectName"
  name: "Project Name"
  description: "The name of your project. Will be used for name generation and must be unique tenant-wide"
  type: "string"
- id: "devPrincipalId"
  name: "Dev Users principal ID"
  description: "The principal ID of the user that will be assigned to the Dev Box project as a Dev Box User"
  type: "string"