apiVersion: azure.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: OIDCTokenFile
  clientID: "<CROSSPLANE_IDENTITY_CLIENT_ID>"
  subscriptionID: "<SUBSCRIPTION_ID>"
  tenantID: "<TENANT_ID>"
